package rabbit.gl.type.copy;

public enum sglEErrorCode
{
	  /// Operation succeeded
	  SGL_NO_ERROR,
	  /// Invalid argument(s) to a call
	  SGL_INVALID_VALUE,
	  /// Invalid enum argument(s) to a call
	  SGL_INVALID_ENUM,
	  /// Invalid call (most typical: sglBegin after another sglBegin,
	  /// state change inside sglBegin/sglEnd pair, no context defined)
	  SGL_INVALID_OPERATION,
	  /// Quota of internal resources exceeded (e.g. number of drawing contexts)
	  SGL_OUT_OF_RESOURCES,
	  /// Internal library error
	  SGL_INTERNAL_ERROR,
	  /// Matrix stack overflow. Generated by sglPushMatrix().
	  SGL_STACK_OVERFLOW,
	  /// Matrix stack underflow - trying to pop matrix when there is only one matrix left on the stack.
	  /// Generated by sglPopMatrix().
	  SGL_STACK_UNDERFLOW,
	  /// Insufficient memory to finish the requested operation
	  SGL_OUT_OF_MEMORY;
}
